# # Development Dockerfile (Dockerfile.dev)
FROM oven/bun:1

WORKDIR /app

RUN apt-get update && apt-get install -y postgresql-client && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY package.json bun.lockb* prisma ./ 

RUN bun install --frozen-lockfile

RUN bun prisma generate

COPY . .

RUN chmod +x /app/entrypoint.sh

EXPOSE 8000

# CMD ["sh", "-c", "bun run db:migrate && bun run dev"]
CMD ["/app/entrypoint.sh"]